// Generated by CoffeeScript 1.3.3
(function() {
  var Filters, Groupers, Sorters, View;

  View = require('./view');

  Sorters = require('./sorters');

  Groupers = require('./groupers');

  Filters = require('./filters');

  module.exports = {
    task_list: function(storage, project) {
      return new View(storage, {
        sort: Sorters.task_list,
        filter: Filters.dsl(function() {
          return this.and(this.tasks, this.in_project(project));
        }),
        group: Groupers.state
      });
    },
    project_list: function(storage) {
      return new View(storage, {
        sort: Sorters.project_list,
        filter: Filters.dsl(function() {
          return this.and(this.projects, this.incomplete);
        })
      });
    }
  };

}).call(this);
