// Generated by CoffeeScript 1.3.3
(function() {
  var constants, _ctor_filter, _state_filter;

  constants = require('../constants');

  _ctor_filter = function(ctor) {
    return function(k, e) {
      return e.constructor && e.constructor.name === ctor;
    };
  };

  _state_filter = function(target) {
    return function(k, e) {
      return e.data && e.data.state && e.data.state === target;
    };
  };

  module.exports = {
    projects: _ctor_filter("NibbanaProject"),
    tasks: _ctor_filter("NibbanaTask"),
    tags: _ctor_filter("NibbanaTag"),
    areas: _ctor_filter("NibbanaArea"),
    contexts: _ctor_filter("NibbanaContext"),
    contacts: _ctor_filter("NibbanaContact"),
    inbox: _state_filter(constants.task.state.INBOX),
    next: _state_filter(constants.task.state.NEXT),
    later: _state_filter(constants.task.state.LATER),
    waiting: _state_filter(constants.task.state.WAITING),
    scheduled: _state_filter(constants.task.state.SCHEDULED),
    someday: _state_filter(constants.task.state.SOMEDAY),
    trashed: _state_filter(constants.task.state.TRASHED),
    deleted: _state_filter(constants.task.state.DELETED),
    completed: function(k, e) {
      return e.data && e.data.completed !== "0";
    },
    incomplete: function(k, e) {
      return e.data && e.data.completed === "0";
    },
    inactive: function(k, e) {
      return e.data && e.data.state && (e.data.state === constants.task.state.LATER || e.data.state === constants.task.state.SOMEDAY);
    },
    focused: function(k, e) {
      return e.data && e.data.seqt && e.data.seqt !== "0";
    },
    in_project: function(p) {
      return function(k, e) {
        return e.data.parentid === p.data.id;
      };
    },
    tagged_with: function(t) {
      return function(k, e) {
        return e.data && e.data.tags && e.data.tags.indexOf(t) > -1;
      };
    },
    and: function(a, b) {
      return function(k, e) {
        return a(k, e) && b(k, e);
      };
    },
    dsl: function(f) {
      return f.apply(this);
    },
    search: function(term) {}
  };

}).call(this);
