// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    state: function(e) {
      return e.data && e.data.state;
    },
    project: function(e) {
      return e.data && e.data.parentid;
    }
  };

}).call(this);
