// Generated by CoffeeScript 1.3.3
(function() {
  var _num_field_sorter;

  _num_field_sorter = function(field) {
    return function(a, b) {
      var av, bv;
      av = parseInt(a.data[field]);
      bv = parseInt(b.data[field]);
      if (av > bv) {
        return 1;
      } else {
        if (av < bv) {
          return -1;
        } else {
          return 0;
        }
      }
    };
  };

  module.exports = {
    task_list: _num_field_sorter("seqp"),
    project_list: _num_field_sorter("seq")
  };

}).call(this);
