// Generated by CoffeeScript 1.3.3
(function() {
  var View;

  View = (function() {

    function View(storage, opts) {
      if (opts == null) {
        opts = {};
      }
      this.sort = opts.sort ? opts.sort : null;
      this.filter = opts.filter ? opts.filter : function() {
        return true;
      };
      this.group = opts.group ? opts.group : null;
      this.storage = storage;
    }

    View.prototype.get = function(params) {
      var e, g, grouped, view, _i, _len;
      if (params == null) {
        params = {};
      }
      view = this.storage.map(this.filter);
      if (this.sort) {
        view = view.sort(this.sort);
      }
      grouped = {};
      if (this.group) {
        for (_i = 0, _len = view.length; _i < _len; _i++) {
          e = view[_i];
          g = this.group(e);
          if (!grouped[g]) {
            grouped[g] = [];
          }
          grouped[g].push(e);
        }
        return grouped;
      }
      return view;
    };

    return View;

  })();

  module.exports = View;

}).call(this);
