// Generated by CoffeeScript 1.3.3
(function() {
  var ObjectStorage;

  ObjectStorage = (function() {

    function ObjectStorage() {
      this.data = {};
      this.dirty = [];
    }

    ObjectStorage.prototype.has = function(key) {
      if (this.data[key]) {
        return true;
      } else {
        return false;
      }
    };

    ObjectStorage.prototype.get = function(key) {
      return this.data[key];
    };

    ObjectStorage.prototype.set = function(key, data, make_dirty) {
      if (make_dirty == null) {
        make_dirty = true;
      }
      this.data[key] = data;
      if (make_dirty) {
        return this.dirty.push(key);
      }
    };

    ObjectStorage.prototype.remove = function(key) {
      return delete this.data[key];
    };

    ObjectStorage.prototype.clear = function(key) {
      var k, v, _ref;
      _ref = this.data;
      for (k in _ref) {
        v = _ref[k];
        delete this.data[key];
      }
      return this.data = {};
    };

    ObjectStorage.prototype.map = function(func) {
      var e, k, mapped, _ref;
      mapped = [];
      _ref = this.data;
      for (k in _ref) {
        e = _ref[k];
        if (func(k, e)) {
          mapped.push(e);
        }
      }
      return mapped;
    };

    ObjectStorage.prototype.clear_dirty = function() {
      return this.dirty = [];
    };

    return ObjectStorage;

  })();

  module.exports = ObjectStorage;

}).call(this);
