// Generated by CoffeeScript 1.3.3
(function() {
  var jq;

  jq = require('jquery');

  module.exports = function() {
    var XMLHttpRequest, mod;
    mod = "xmlhttprequest";
    XMLHttpRequest = require(mod).XMLHttpRequest;
    jq.support.cors = true;
    return jq.ajaxSettings.xhr = function() {
      return new XMLHttpRequest;
    };
  };

}).call(this);
