// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    unix_time: function(date) {
      if (date == null) {
        date = new Date;
      }
      return Math.floor(date.getTime() / 1000);
    }
  };

}).call(this);
