// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractTask, Project, Task, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractTask = require('./abstract');

  Project = require('./project');

  constants = require('../constants');

  Task = (function(_super) {

    __extends(Task, _super);

    function Task(data, storage) {
      this.type = constants.task.type.TASK;
      Task.__super__.constructor.call(this, data, storage);
    }

    Task.prototype.to_project = function() {
      var active, p;
      active = this.data.state !== constants.task.state.LATER && this.data.state !== constants.task.state.SOMEDAY;
      if (active) {
        this.state(constants.task.state.ACTIVE_PROJECT);
      }
      this._set("type", constants.task.type.PROJECT);
      p = new Project(this.data);
      p.dirty = this.dirty;
      return p;
    };

    Task.prototype.set_parent = function(parent) {
      if (typeof parent === "object" && parent.id) {
        parent = parent.id;
      }
      this._set("parentid", parent);
      return this;
    };

    Task.prototype.parentid = function(parentid) {
      if (parentid === void 0) {
        return this.data.parentid;
      }
      this._set("parentid", parentid);
      return this;
    };

    Task.prototype.parent = function(parent) {
      if (parent === void 0) {
        return this.storage.get(this.parentid());
      }
      this._set("parentid", parent.id);
      return this;
    };

    Task.prototype.schedule_for = function(start) {
      this._set("startdate", start ? start : "");
      this.state(constants.task.state.SCHEDULED);
      return this;
    };

    Task.prototype.scheduled_for = function() {
      return this.data.startdate;
    };

    Task.prototype.is_recurring = function() {
      return this.data.recurring !== null;
    };

    Task.prototype.estimated_time = function(time) {
      if (time === void 0) {
        return this.data.etime;
      }
      this._set("etime", time);
      return this;
    };

    Task.prototype.energy = function(energy) {
      if (energy === void 0) {
        return this.data.energy;
      }
      this._set("energy", energy);
      return this;
    };

    return Task;

  })(AbstractTask);

  module.exports = Task;

}).call(this);
