module.exports =
  View: require( './view/view' )
  ViewFactory: require( './view/factory' )
  Session: require( './session' )
  LocalStorage: require( './storage/local' )
  ObjectStorage: require( './storage/object' )
  Task: require( './task/task' )
  Project: require( './task/project' )
  Tag: require( './tag/tag' )
  Area: require( './tag/area' )
  Context: require( './tag/context' )
  Contact: require( './tag/contact')
  Constants: require( './constants' )
  cors_hack: require( './cors_hack' )