// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractTag, jq, util;

  jq = require('jquery');

  util = require('../util');

  AbstractTag = (function() {

    function AbstractTag(data) {
      this.data = this.template(data);
      this.dirty = [];
    }

    AbstractTag.prototype.get_data = function() {
      return jq.extend({
        "__internal_type": this.constructor.name
      }, this.data);
    };

    AbstractTag.prototype.store_key = function() {
      return "tag-" + this.data.key;
    };

    AbstractTag.prototype.template = function(data) {
      var tpl;
      tpl = {
        key: "",
        type: this.type,
        email: "",
        color: "",
        meta: "",
        deleted: 0
      };
      return jq.extend(tpl, data);
    };

    AbstractTag.prototype.key = function(key) {
      if (key === void 0) {
        return this.data.key;
      }
      this.data.key = key;
      this.dirty.push("key");
      return this;
    };

    AbstractTag.prototype.color = function(color) {
      if (color === void 0) {
        return this.data.color;
      }
      this.data.color = color;
      this.dirty.push(color);
      return this;
    };

    AbstractTag.prototype["delete"] = function() {
      this.data.deleted = util.unix_time();
      this.dirty.push("deleted");
      return this;
    };

    AbstractTag.prototype.is_deleted = function() {
      return this.data.deleted > 0;
    };

    return AbstractTag;

  })();

  module.exports = AbstractTag;

}).call(this);
