// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractTag, Area, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractTag = require('./abstract');

  constants = require('../constants');

  Area = (function(_super) {

    __extends(Area, _super);

    function Area(data) {
      this.type = constants.tag.type.AREA;
      Area.__super__.constructor.call(this, data);
    }

    return Area;

  })(AbstractTag);

  module.exports = Area;

}).call(this);
