// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractTag, Contact, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractTag = require('./abstract');

  constants = require('../constants');

  Contact = (function(_super) {

    __extends(Contact, _super);

    function Contact(data) {
      this.type = constants.tag.type.CONTACT;
      Contact.__super__.constructor.call(this, data);
    }

    Contact.prototype.email = function(email) {
      if (email === "undefined") {
        return this.data.email;
      }
      this.data.email = email;
      this.dirty.push("email");
      return this;
    };

    return Contact;

  })(AbstractTag);

  module.exports = Contact;

}).call(this);
