// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractTag, Context, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractTag = require('./abstract');

  constants = require('../constants');

  Context = (function(_super) {

    __extends(Context, _super);

    function Context(data) {
      this.type = constants.tag.type.CONTEXT;
      Context.__super__.constructor.call(this, data);
    }

    return Context;

  })(AbstractTag);

  module.exports = Context;

}).call(this);
