// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractTag, Tag, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractTag = require('./abstract');

  constants = require('../constants');

  Tag = (function(_super) {

    __extends(Tag, _super);

    function Tag(data) {
      this.type = constants.tag.type.TAG;
      Tag.__super__.constructor.call(this, data);
    }

    return Tag;

  })(AbstractTag);

  module.exports = Tag;

}).call(this);
